-- EdZure Legal LLP Database Schema

CREATE DATABASE IF NOT EXISTS edzure_legal;
USE edzure_legal;

-- Admin Table
CREATE TABLE IF NOT EXISTS admins (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) UNIQUE NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Insights Table (Blogs/News)
CREATE TABLE IF NOT EXISTS insights (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255) UNIQUE NOT NULL,
    content LONGTEXT NOT NULL,
    excerpt TEXT,
    image_url VARCHAR(500),
    image_type ENUM('local', 'online') DEFAULT 'local',
    category ENUM('blog', 'news') DEFAULT 'blog',
    author VARCHAR(100),
    status ENUM('draft', 'published') DEFAULT 'draft',
    views INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    published_at TIMESTAMP NULL,
    INDEX idx_slug (slug),
    INDEX idx_status (status),
    INDEX idx_category (category),
    INDEX idx_created_at (created_at)
);

-- Insert default admin (password: admin123)
INSERT INTO admins (username, email, password) 
VALUES ('admin', 'admin@edzurelegal.com', '$2a$10$YourHashedPasswordHere');

-- Note: You need to hash the password using bcrypt before inserting
-- The password 'admin123' hashed will be generated by the backend on first run